let data = {
    usuario :  [
        {
            email: 'MGimenezRojas@gmail.com',
            nombreDeUsuario:'MatiGimenez34',
            contrasena:'',
            fotoPerfil:'',
            fechaDeNacimiento:'06/03/1999',
            Dni:'41.683.316',
            logueado:true
        },
        {
            email: 'MGimenezRojas@gmail.com',
            nombreDeUsuario:'MatiGimenez34',
            contrasena:'',
            fotoPerfil:'',
            fechaDeNacimiento:'06/03/1999',
            Dni:'41.683.316',
            logueado:true
        },
        {
            email: 'MGimenezRojas@gmail.com',
            nombreDeUsuario:'MatiGimenez34',
            contrasena:'',
            fotoPerfil:'',
            fechaDeNacimiento:'06/03/1999',
            Dni:'41.683.316',
            logueado:true
        },
        {
            email: 'MGimenezRojas@gmail.com',
            nombreDeUsuario:'MatiGimenez34',
            contrasena:'',
            fotoPerfil:'',
            fechaDeNacimiento:'06/03/1999',
            Dni:'41.683.316',
            logueado:true
        },
        {
            email: 'MGimenezRojas@gmail.com',
            nombreDeUsuario:'MatiGimenez34',
            contrasena:'',
            fotoPerfil:'',
            fechaDeNacimiento:'06/03/1999',
            Dni:'41.683.316',
            logueado:true
        },
    ],
    posteos:[
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        },
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        },
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        },
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        },
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        },
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        },
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        },
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        },
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        },
        {
            idUser:'',
            imagen:'',
            descripcion:'',
        }

    ],
    comentarios:[
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        },
        {
            nombreDeUs:'',
            textoDelComentario:'',
            fotoDePer:''
        }
    ]


    
}
module.exports = data